credentials:
  usernames:
    admin@varnixum.com:
      name: Admin Varnixum
      password: $2b$12$vdfvKgpicYGN6rqAHK1a4u6IXTenLLJCNZa3MeQftjjvuNcvn.yhu
    user1@varnixum.com:
      name: User One
      password: $2b$12$Esb9mGZdosam/BpgCEA3teeGl1PGaPHBvj.eRS9XBMAAVPR2Goir2

cookie:
  name: varnixum_cookie
  key: supersecretkey
  expiry_days: 30

preauthorized:
  emails:
    - guest@varnixum.com
